services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      WAIT_HOSTS: mysql:${DB_PORT}, redis:${REDIS_PORT}, broker:${BROKER_PORT}, otel-collector:${OTEL_EXPORTER_OTLP_PORT}
      WAIT_TIMEOUT: 50
    volumes:
      - .:/usr/src/app
      - ./wait:/wait
    ports:
      - ${APP_PORT}:${APP_PORT}
      - ${APP_DEBUG}:${APP_DEBUG}
    command: sh -c  "chmod +x /wait && /wait && npm run start:debug"
    networks:
      - infra
      - monitoring

  flyway:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./migrations.Dockerfile
    volumes:
      - ./migrations/sql:/flyway/sql
      - ./wait:/wait
    env_file:
      - .env
    environment:
      FLYWAY_EDITION: community
      WAIT_HOSTS: mysql:${DB_PORT}
      WAIT_TIMEOUT: 50
    command: sh -c  "chmod +x /wait && /wait && ./flyway -url='jdbc:mysql://mysql:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&useSSL=false' -schemas=${DB_NAME} -user=${DB_USER} -password=${DB_PASSWORD} migrate"
    networks:
      - infra
networks:
  infra:
  monitoring:
    driver: bridge
